
- hosts: loadbalancer
  become: yes
  roles:
    - ./../roles/docker
    - ./../roles/docker_containers
  vars:
    - nginx_config_dest: /var/www/nginx.conf
  tasks:
    - name: Verify /var/www/ exists
      file:
        path: /var/www
        state: directory
        mode: 0755
    - name: Add Nginx Config
      template:
        src: ./../templates/nginx.conf
        dest: "{{ nginx_config_dest }}"
      register: nginx_conf_dict
    - debug: msg="{{ nginx_conf_dict }}"
    - set_fact:
        nginx_lb_conf_path:  "{{ nginx_config_dest }}"
    - debug: msg="{{ nginx_lb_conf_path }}"
    - name: Debug Docker-based Nginx Conf
      vars:
        - _nginx_lb_path: /etc/nginx/conf.d/default.conf
      debug: msg="{{ nginx_lb_conf_path | default(_nginx_lb_path) }}"
    - name: Trigger Docker Container Changes
      shell: echo "Triggering docker changes"
      notify:
        - docker stop containers
        - docker remove containers
        - docker run nginx lb
      when: nginx_conf_dict.changed == true
