
- hosts: loadbalancer
  become: yes
  roles:
    - ./../roles/nginx_purge
    - ./../roles/docker
  tasks:
    - name: Add Nginx Config
      template:
        src: ./../templates/nginx.conf
        dest: /etc/nginx/sites-available/default
      notify: reload nginx
    - name: Enable New Nginx Config
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link