
- hosts: loadbalancer
  become: yes
  roles:
    - ./../roles/nginx_purge
    - ./../roles/docker
  tasks:
    - name: Verify /var/www/ exists
      file:
        path: /var/www
        state: directory
        mode: 0755
    - name: Add Nginx Config
      template:
        src: ./../templates/nginx.conf
        dest: /var/www/nginx.conf
    - name: Has Running Docker Images
      shell: docker ps -aq >/dev/null 2>&1
      register: containers_running
      ignore_errors: yes
    - name: Docker Stop Running Containers
      shell: docker stop $(docker ps -aq)
      when: containers_running.rc == 0
    - name: Docker Remove Previous Containers
      shell: docker rm $(docker ps -aq)
      when: containers_running.rc == 0
    - name: Run Docker-based Nginx
      shell: |
        docker run \
        -v /var/www/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
        -p 80:80 \
        -d nginx