---
- hosts: all
  become: yes
  vars:
      title: Hello there
      description: Some more news!
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Update Nginx Default Homepage
      template:
        dest: /var/www/html/index.nginx-debian.html
        src: ./templates/nginx.default.html