# This is a basic workflow to help you get started with Actions

name: Ansible Playbook via CFE

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Ansible
        run: |
          pip install ansible cfe
      - name: Create PEM Key
        run: |
          cat << EOF > devops/ansible/private.pem
          ${{ secrets.ANSIBLE_PRIVATE_KEY }}
          EOF
      - name: Update key permissions
        run: |
          chmod 400 devops/ansible/private.pem
      - name: Add PEM Key Path to Ansible Config
        run: |
          cat << EOF > devops/ansible/ansible.cfg
          [defaults]
          ansible_python_interpreter='/usr/bin/python3'
          deprecation_warnings=False
          inventory=./inventory.ini
          remote_user="root"
          retries=2
          private_key_file = ./private.pem
          EOF
      - name: Adding the Inventory
        run: |
          LINODE_ACCEES_TOKEN=${{ secrets.LINODE_ACCESS_TOKEN }} \
          cfe services linode inventory \ 
          --save-path "devops/ansible/inventory.ini" \
          --tags "webapps,loadbalancer"
      - name: Run main playbook
        run: |
          cd devops/ansible
          ansible-playbook main.yaml